apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloud-native-platform
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "cloud_native_platform"
  S3_BUCKET: "cloud-native-platform-attachments"
  S3_REGION: "us-east-1"
  CLIENT_ORIGIN: "https://app.example.com"
  JWT_EXPIRE_MINUTES: "10080"
